### PR TITLE
check if the environment and robot paths were informed

### PR DESCRIPTION
**Pull request by gustavoneves12**
This PR checks if the environment and robot paths were informed. If these paths are not informed, the OMPL will select the default environment.

How to test
---------------

Use the unit tests to check if this modification affected the previous code:

```bash
autoproj test enable planning/ompl_geometric_planning
acd planning/ompl_geometric_planning
amake
./build/test/planning_test
```

### CODE REVIEW

**Comment by renan028** [comment]
I don't get it. That is just to avoid a throw?

**Comment by gustavoneves12** [comment]
Yes, @renan028! I would like to add the possibility to call the planning without informing the environment.

**Comment by renan028** [comment]
But you don’t need the GeometricPlanningMesh to stop a robot. That class is a Façade for planning using meshes. setup is protected, so you will not be able to change it later (with a mesh). 

Can you explain to me what you want to do?
stopRobot is a function in Utils.hpp (you don’t need a planner)

**Comment by gustavoneves12** [comment]
@renan028, I indeed don't need the `GeometricPlanningMesh` for stopping the robot, however, for creating the unit tests to the `stopRobot` operation, I will need to call at least the `GeometricPlanning` for creating the trajectories.

I initially included this verification to allow running these unit tests without informing the STL meshes. After think about you said, I agree with you and I think `GeometricPlanningMesh` show throw an exception in case of those parameters are not informed.

Anyhow, the tests are passing, if without these modifications. See the output below:

```bash
Run options: --seed 48551

# Running:

.Error:   Unable to load environment scene: 
         at line 92 in /home/gustavoneves/squidbot/planning/omplapp/src/omplapp/geometry/RigidBodyGeometry.cpp
Error:   Unable to load robot scene: 
         at line 49 in /home/gustavoneves/squidbot/planning/omplapp/src/omplapp/geometry/RigidBodyGeometry.cpp
BVH Error! endModel() called on model with no triangles and vertices.
Info:    Empty environment loaded
Info:    No planner specified. Using default.
Info:    LBKPIECE1: Attempting to use default projection.
Debug:   LBKPIECE1: Planner range detected to be 70.289012
Debug:   InformedRRTstar: Planner range detected to be 3.085441
Info:    InformedRRTstar: No optimization objective specified. Defaulting to optimizing path length for the allowed planning time.
Info:    InformedRRTstar: Using informed sampling.
Info:    InformedRRTstar: Started planning with 1 states. Seeking a solution better than 0.00000.
Info:    InformedRRTstar: Initial k-nearest value of 310
Info:    InformedRRTstar: Found an initial solution with a cost of 16.27 in 14 iterations (15 vertices in the graph)
Info:    InformedRRTstar: Created 3719 new states. Checked 1897649 rewire options. 1 goal states in tree. Final solution cost 7.341
Info:    Solution found in 0.500456 seconds
.Error:   Unable to load environment scene: 
         at line 92 in /home/gustavoneves/squidbot/planning/omplapp/src/omplapp/geometry/RigidBodyGeometry.cpp
Error:   Unable to load robot scene: 
         at line 49 in /home/gustavoneves/squidbot/planning/omplapp/src/omplapp/geometry/RigidBodyGeometry.cpp
BVH Error! endModel() called on model with no triangles and vertices.
Info:    Empty environment loaded
Info:    No planner specified. Using default.
Info:    LBKPIECE1: Attempting to use default projection.
Debug:   LBKPIECE1: Planner range detected to be 70.289012
Debug:   InformedRRTstar: Planner range detected to be 2.046210
Info:    InformedRRTstar: No optimization objective specified. Defaulting to optimizing path length for the allowed planning time.
Info:    InformedRRTstar: Using informed sampling.
Info:    InformedRRTstar: Started planning with 1 states. Seeking a solution better than 0.00000.
Info:    InformedRRTstar: Initial k-nearest value of 310
Info:    InformedRRTstar: Found an initial solution with a cost of 1.73 in 24 iterations (25 vertices in the graph)
Info:    InformedRRTstar: Created 2066 new states. Checked 2088245 rewire options. 1 goal states in tree. Final solution cost 1.732
Info:    Solution found in 0.500144 seconds
.

Finished in 4.567617s, 0.6568 runs/s, 3.0651 assertions/s.

3 runs, 14 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by gustavoneves12** [comment]
I am going to close this PR and later we include the possibility to call `GeometricPlanning` without informing the STL meshes.

**Comment by renan028** [comment]
That is possible. Actually, GeometricPlanning has a default constructor (no parameters).
And yes, GeometricPlanningMesh with no mesh works, but throws a warning. It will create an empty world and an empty robot and it warns the developer about that. All states are valid (Because there aren’t collisions).

Do you think that behavior is not expected? I would agree with an assertion after loading an empty environment. Like throwing an actual error and not just a warning.

**Pull request closed without merging**
